### ISSUE TITLE
storeconfigs

### ISSUE THREAD

**Issue by rudgab** [ghoneycutt/puppet-module-hosts#49]
Hi, 

a puppet parser validate manifests/init.pp yields:
Warning: You cannot collect without storeconfigs being set on line 128 in file /etc/puppet/environments/production/modules/hosts/manifests/init.pp
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 134 in file /etc/puppet/environments/production/modules/hosts/manifests/init.pp
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored on line 138 in file /etc/puppet/environments/production/modules/hosts/manifests/init.pp

What's going on?

Regards,

Rudi G.

**Comment by edestecd** [comment]
How about putting an if $storeconfigs_enabled around those blocks?

**Comment by edestecd** [comment]
Another option is this:
```puppet
if $::settings::storeconfigs {
  # things that require puppetdb
}
```

**Comment by ghoneycutt** [comment]
Thanks to everyone involved. I've been very hesitant to accept any changes to this module because bugs in /etc/hosts can have a critical impact to systems. In order to make changes, I'm working on adding functional testing through Vagrant which will be released in V3 of this module.

Storeconfigs will not be present in v3 of the module, instead leaving that up to use in profiles.

PR #49 may be of interest to you, since it conditionally exports resources. I could use feedback on that PR.
