### ISSUE TITLE
Allow for selection of IP on multi-homed host

### ISSUE THREAD

**Issue by JockMacMad** [ghoneycutt/puppet-module-hosts#64]
At present when running on a multi-homed host I see no way to specify which adapter and hence IP address to use. When testing the module we noticed that the IP allocated to the hostname was different to our manual setup due to this.

Is it possible to get a parameter like ${::public_if} so that the value can be picked up dynamically.

e.g. Host _FooBar_ with 2 NICS _eth0_ and _eth1_, _eth0_ is the management interface and _eth1_ is the public interface. _eth0_ has IP _10.204.2.117_ and _eth1_ has 10.204.3.5 

We would like to end up with:-

_10.204.3.5 FooBar_

but currently we are fixed at getting:-

_10.204.2.117 FooBar_

using a parameter along the lines of :-

_public_ip = ${::public_if}_ where _${::public_if}_ is set to _eth1_ (as a string)

Many thanks

**Comment by ghoneycutt** [comment]
Thanks to everyone involved. I've been very hesitant to accept any changes to this module because bugs in /etc/hosts can have a critical impact to systems. In order to make changes, I'm working on adding functional testing through Vagrant which will be released in V3 of this module.

This functionality is being added to V3 of this module in PR #65
